### ISSUE TITLE
Update to Julia v1

### ISSUE THREAD

**Issue by briochemc** [rafaqz/UnitfulMoles.jl#1]
I was going to submit an issue on Unitful.jl and stumbled on https://github.com/PainterQubits/Unitful.jl/issues/124, which led me here... I did not know about these! However, I just tried UnitfulMoles.jl on Julia v1.3 and it does not work. Any chance this package (and the accompanying one with conventional units) could be revived, updated, and tested on the latest Julia versions?

**Comment by rafaqz** [comment]
This is really old! probably from 0.6 (one of the first packages I wrote)

There are some weird things like the auto mol-gram conversions for compounds that might not really make sense or have good performance, but I thought were super cool when I wrote it. 

I don't have any time to revive it, I ended up not using it in my research and just using regular Mols, but do what you like with it.
