### ISSUE TITLE
Interaction with Pluto notebook: @compound macro

### ISSUE THREAD

**Issue by rc83** [rafaqz/UnitfulMoles.jl#12]
I would like to use this module inside a Pluto notebook (by @fonsp at https://github.com/fonsp/Pluto.jl/). However I run into issues with the `@compound` macro. When the notebook cell is run for the first time, a new variable is defined, I believe. However any subsequent re-run of the cell raises an error as shown bellow (the number of workspace6 increments in every re-run).

The notebook cell:
```
@compound NaOH
```

1st execution (OK):
```
molNaOH
```

2nd execution (error):
```
cannot assign a value to variable workspace5.EmolNaOH from module workspace6

    top-level scope@Local: 243
    top-level scope@Parse.jl:111
    (::Distributed.var"#101#102"{Distributed.CallMsg{:call}})()@process_messages.jl:290
    run_work_thunk(::Distributed.var"#101#102"{Distributed.CallMsg{:call}}, ::Bool)@process_messages.jl:79
    run_work_thunk(::Distributed.RemoteValue, ::Function)@process_messages.jl:88
    (::Distributed.var"#94#96"{Distributed.RemoteValue,Distributed.var"#101#102"{Distributed.CallMsg{:call}}})()@task.jl:358
```

As it runs without issues in Julia on terminal, it is difficult for me to determine whether this issue is more _UnitfulMoles_ or _Pluto_ related. Any help is greatly appreciated! Thank you very much!

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/issues/196#issuecomment-650415188

**Comment by rafaqz** [comment]
Yeah that's on Pluto. I guess Pluto needs to be seen as an incomplete implementation of Julia.This should work in a Jupyter notebook.

This package just defines standard Unitful objects and methods, which you can do manually. The problem it has to define a lot to make these things all just work. That one line generates like 80 lines of code. That's the perfect job for a macro.

**Comment by rc83** [comment]
Thank you, @fonsp and @rafaqz, for your excellent support and clarification! I am closing this issue as not-a-bug because it does not origin from _UnitfulMoles_.
